# Generated by Django 4.1.5 on 2023-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_experience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
