# Generated by Django 4.1.5 on 2023-08-05 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('resume_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(default='05e1cspzbkkh2kx4pg14')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(blank=True, choices=[('LANGUAGE', 'LANGUAGE'), ('DATABASE', 'DATABASE'), ('FRAMEWORK', 'FRAMEWORK'), ('SOFTWARE', 'SOFTWARE'), ('CLOUD_PLATFORM', 'CLOUD_PLATFORM'), ('PARADIGM', 'PARADIGM')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('company_description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_work', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='techskill', to='resume.tech'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=400)),
                ('github', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('field', models.CharField(blank=True, choices=[('BSC SCIENCE', 'BSC SCIENCE'), ('BSC ENGINEERING', 'BSC ENGINEERING'), ('BSC FINANCE', 'BSC FINANCE'), ('BSC ECONOMICS AND BUSINESS', 'BSC ECONOMICS AND BUSINESS'), ('BSC APPLIED SCIENCES', 'BSC APPLIED SCIENCES'), ('BOOTCAMP', 'BOOTCAMP'), ('BSC LAW', 'BSC LAW')], max_length=300, null=True)),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_edu', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
