# Generated by Django 3.2.15 on 2022-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='x45vypdzqoo7hz4950m6'),
        ),
    ]
