# Generated by Django 3.2.15 on 2023-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='jbrn7wokdgwshakt4p11'),
        ),
    ]
