# Generated by Django 3.2.15 on 2022-09-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='i8629m0j0pb6nb8urf0h'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='type',
            field=models.CharField(blank=True, choices=[('LANGUAGE', 'LANGUAGE'), ('DATABASE', 'DATABASE'), ('FRAMEWORK', 'FRAMEWORK'), ('LIBRARY', 'LIBRARY'), ('SOFTWARE', 'SOFTWARE'), ('CLOUD_PLATFORM', 'CLOUD_PLATFORM'), ('PARADIGM', 'PARADIGM')], max_length=200, null=True),
        ),
    ]
