# Generated by Django 3.2.15 on 2022-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20220923_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='g6zweh5u7fmaw72xpcnq'),
        ),
    ]
