# Generated by Django 3.2.15 on 2022-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20220923_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='lj9jabrdf5hli97ji54z'),
        ),
    ]
