# Generated by Django 4.2.6 on 2023-11-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='v7i1wpc7yw1on6ytufy9'),
        ),
    ]
