# Generated by Django 4.2.6 on 2024-04-02 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='eray7dsrg5betdoodqyr'),
        ),
        migrations.AlterField(
            model_name='work',
            name='company_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
