# Generated by Django 4.1 on 2022-08-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_project_resume_link_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='resume.project'),
        ),
    ]
