# Generated by Django 4.1 on 2022-08-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_project_resume_alter_experience_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resume.resume'),
        ),
    ]
