# Generated by Django 3.2.15 on 2022-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20220924_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='0d901cdwcorwewfkmk9c'),
        ),
    ]
