# Generated by Django 4.1 on 2022-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_userprofile_email_userprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_profile',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
