# Generated by Django 4.1 on 2022-09-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_userprofile_has_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
