# Generated by Django 4.1 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
