# Generated by Django 4.1 on 2022-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_work_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='company_description',
            field=models.CharField(max_length=250),
        ),
    ]
