# Generated by Django 4.1 on 2022-09-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_work_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='rqq0e8ib3jo4c41f3chz'),
        ),
    ]
