# Generated by Django 4.1 on 2022-09-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='7ghhhh1fohcp8riqmqfh'),
        ),
    ]
