# Generated by Django 3.2.15 on 2022-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_alter_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='j0dfxeamxc6cujfmgyab'),
        ),
    ]
