# Generated by Django 3.2.15 on 2022-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_alter_resume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='5wd60f49xxy9wro492w8'),
        ),
    ]
