# Generated by Django 3.2.15 on 2022-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_auto_20220915_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='zp2hl74c027p7b5q7tri'),
        ),
    ]
