# Generated by Django 3.2.15 on 2022-09-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_alter_resume_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Contract', 'Contract')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='ovze3igli85vi12nynkb'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tech_skill',
            field=models.ManyToManyField(blank=True, null=True, to='resume.Tech'),
        ),
    ]
