# Generated by Django 3.2.15 on 2022-09-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_auto_20220918_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='5gf3qlkyocb3xvdftanq'),
        ),
    ]
