# Generated by Django 3.2.15 on 2022-09-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0030_alter_resume_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tech',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tech_skill',
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='4c8btbxslbrvu2dwi5r4'),
        ),
    ]
