# Generated by Django 3.2.15 on 2022-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0035_auto_20220919_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks_lib_software',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='languages_db_paradim',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='mmn47qb9gdn22nwkjwwc'),
        ),
    ]
