# Generated by Django 3.2.15 on 2022-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0036_auto_20220919_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('LANGUAGE', 'LANGUAGE'), ('DATABASE', 'DATABASE'), ('FRAMEWORK', 'FRAMEWORK'), ('LIBRARY', 'LIBRARY'), ('SOFTWARE', 'SOFTWARE'), ('CLOUD_PLATFORM', 'CLOUD_PLATFORM'), ('PARADIGM', 'PARADIGM')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='fr_lb_sw',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='la_db_pd',
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='3q04kv1mpupmctxuhpsl'),
        ),
        migrations.DeleteModel(
            name='Frameworks_LIB_Software',
        ),
        migrations.DeleteModel(
            name='Languages_DB_Paradim',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resume.Tech'),
        ),
    ]
