# Generated by Django 3.2.15 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0037_auto_20220919_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='techskill', to='resume.Tech'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default='4uxiubg6sz99k17yc7gl'),
        ),
    ]
